version: 2

updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "07:00"
      timezone: Europe/Amsterdam
    open-pull-requests-limit: 5
    groups:
      astro:
        patterns:
          - astro
          - "@astrojs/*"
      pagefind:
        patterns:
          - pagefind
          - "@pagefind/*"
      tooling:
        patterns:
          - "@typescript-eslint/*"
          - eslint*
          - linkinator
          - prettier*
          - typescript

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "07:00"
      timezone: Europe/Amsterdam
    open-pull-requests-limit: 5
